set -sg escape-time 0
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g detach-on-destroy off     # Stay in tmux when session closes
set -g renumber-windows on       # No gaps after closing windows

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
#
# # Vim style pane selection
bind -n M-M select-pane -L
bind -n M-I select-pane -R
bind -n M-E select-pane -U
bind -n M-N select-pane -D
bind -n M-O resize-pane -Z

bind -n M-S-Left resize-pane -L 2
bind -n M-S-Right resize-pane -R 2
bind -n M-S-Up resize-pane -U 2
bind -n M-S-Down resize-pane -D 2
#
bind-key L split-window -h \; select-layout "4b64,213x61,0,0[213x44,0,0,29,213x16,0,45,35]"
# # Use Alt-arrow keys without prefix key to switch panes
# bind -n M-Left select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up select-pane -U
# bind -n M-Down select-pane -D
#
bind o select-pane -t :.+ -Z # cycle to next pane, staying zoomed
#
# # Shift arrow to switch windows
# bind -n S-Left  previous-window
# bind -n S-Right next-window
#
# # Shift Alt vim keys to switch windows
# bind -n M-H previous-window
# bind -n M-L next-window

# set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'

# # set vi-mode
# set-window-option -g mode-keys vi
# # keybindings
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
#
# bind '"' split-window -v -c "#{pane_current_path}"
# bind % split-window -h -c "#{pane_current_path}"
set -g status off
set-option -sa terminal-features ',alacritty:RGB'

# Make kitty image protocol available to neovim
set -g allow-passthrough on
set -g extended-keys on

# How it looks
set-window-option -g window-style 'bg=#171d28'
set-window-option -g window-active-style 'bg=#19202c'

set -g pane-border-style "bg=#0c1016 fg=#19202c"
set -g pane-active-border-style "bg=#0c1016 fg=#19202c"

bind Q display-message 'Pane: #{pane_id}'
