set -sg escape-time 10
set -as terminal-features ",xterm*:RGB,alacritty:RGB"
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g detach-on-destroy off     # Stay in tmux when session closes
set -g renumber-windows on       # No gaps after closing windows

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind -n M-M select-pane -L
bind -n M-I select-pane -R
bind -n M-E select-pane -U
bind -n M-N select-pane -D
bind -n M-O resize-pane -Z

bind -n M-S-Left resize-pane -L 2
bind -n M-S-Right resize-pane -R 2
bind -n M-S-Up resize-pane -U 2
bind -n M-S-Down resize-pane -D 2
bind o select-pane -t :.+ -Z # cycle to next pane, staying zoomed

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'

set -g status off

# Make kitty image protocol available to neovim
set -g allow-passthrough on
set -g extended-keys on

# How it looks
set-window-option -g window-style 'bg=#171d28'
set-window-option -g window-active-style 'bg=#19202c'

set -g pane-border-style "bg=#0c1016 fg=#19202c"
set -g pane-active-border-style "bg=#0c1016 fg=#19202c"

bind Q display-message 'Pane: #{pane_id}'
